-- Aurum Quant licensing backend schema.
-- Deployment target: a dedicated Supabase project. Do not apply to unrelated application projects.

create extension if not exists pgcrypto;

create table if not exists public.aurum_licenses (
  id uuid primary key default gen_random_uuid(),
  key_hash text not null unique check (key_hash ~ '^[0-9a-f]{64}$'),
  status text not null default 'active' check (status in ('active','revoked')),
  plan text not null default 'commercial',
  expires_at timestamptz,
  max_activations smallint not null default 1 check (max_activations between 1 and 20),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.aurum_license_activations (
  id bigint generated by default as identity primary key,
  license_id uuid not null references public.aurum_licenses(id) on delete cascade,
  account_fingerprint text not null check (account_fingerprint ~ '^[0-9a-f]{64}$'),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  last_version text not null check (char_length(last_version) between 1 and 32),
  active boolean not null default true,
  unique (license_id, account_fingerprint)
);

create table if not exists public.aurum_license_events (
  id bigint generated by default as identity primary key,
  license_id uuid references public.aurum_licenses(id) on delete set null,
  key_hash text not null check (key_hash ~ '^[0-9a-f]{64}$'),
  account_fingerprint text not null check (account_fingerprint ~ '^[0-9a-f]{64}$'),
  version text not null check (char_length(version) between 1 and 32),
  decision text not null check (decision in ('VALID','INVALID','REVOKED','EXPIRED','ACTIVATION_LIMIT')),
  created_at timestamptz not null default now()
);

create index if not exists aurum_license_events_rate_idx
  on public.aurum_license_events (key_hash, account_fingerprint, created_at desc);
create index if not exists aurum_license_activations_license_idx
  on public.aurum_license_activations (license_id, active);

alter table public.aurum_licenses enable row level security;
alter table public.aurum_license_activations enable row level security;
alter table public.aurum_license_events enable row level security;

revoke all on table public.aurum_licenses from public, anon, authenticated;
revoke all on table public.aurum_license_activations from public, anon, authenticated;
revoke all on table public.aurum_license_events from public, anon, authenticated;

grant select, insert, update, delete on table public.aurum_licenses to service_role;
grant select, insert, update, delete on table public.aurum_license_activations to service_role;
grant select, insert on table public.aurum_license_events to service_role;
grant usage, select on sequence
  public.aurum_license_activations_id_seq,
  public.aurum_license_events_id_seq
to service_role;

create or replace function public.aurum_validate_license(
  p_key_hash text,
  p_account_fingerprint text,
  p_version text
)
returns table(decision text, expires_unix bigint)
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_license public.aurum_licenses%rowtype;
  v_recent_requests bigint;
  v_activation_count bigint;
begin
  if p_key_hash is null
     or p_key_hash !~ '^[0-9a-f]{64}$'
     or p_account_fingerprint is null
     or p_account_fingerprint !~ '^[0-9a-f]{64}$'
     or p_version is null
     or char_length(p_version) < 1
     or char_length(p_version) > 32 then
    return query select 'INVALID'::text, 0::bigint;
    return;
  end if;

  select count(*)
    into v_recent_requests
    from public.aurum_license_events e
   where e.key_hash = p_key_hash
     and e.account_fingerprint = p_account_fingerprint
     and e.created_at >= now() - interval '10 minutes';

  if v_recent_requests >= 30 then
    return query select 'RATE_LIMITED'::text, 0::bigint;
    return;
  end if;

  select *
    into v_license
    from public.aurum_licenses l
   where l.key_hash = p_key_hash
   for update;

  if not found then
    insert into public.aurum_license_events(key_hash, account_fingerprint, version, decision)
    values (p_key_hash, p_account_fingerprint, p_version, 'INVALID');
    return query select 'INVALID'::text, 0::bigint;
    return;
  end if;

  if v_license.status = 'revoked' then
    insert into public.aurum_license_events(license_id, key_hash, account_fingerprint, version, decision)
    values (v_license.id, p_key_hash, p_account_fingerprint, p_version, 'REVOKED');
    return query select 'REVOKED'::text, 0::bigint;
    return;
  end if;

  if v_license.expires_at is not null and now() >= v_license.expires_at then
    insert into public.aurum_license_events(license_id, key_hash, account_fingerprint, version, decision)
    values (v_license.id, p_key_hash, p_account_fingerprint, p_version, 'EXPIRED');
    return query select 'EXPIRED'::text, extract(epoch from v_license.expires_at)::bigint;
    return;
  end if;

  update public.aurum_license_activations
     set last_seen_at = now(), last_version = p_version
   where license_id = v_license.id
     and account_fingerprint = p_account_fingerprint
     and active = true;

  if not found then
    select count(*)
      into v_activation_count
      from public.aurum_license_activations a
     where a.license_id = v_license.id
       and a.active = true;

    if v_activation_count >= v_license.max_activations then
      insert into public.aurum_license_events(license_id, key_hash, account_fingerprint, version, decision)
      values (v_license.id, p_key_hash, p_account_fingerprint, p_version, 'ACTIVATION_LIMIT');
      return query select 'ACTIVATION_LIMIT'::text,
        coalesce(extract(epoch from v_license.expires_at)::bigint, 0::bigint);
      return;
    end if;

    insert into public.aurum_license_activations(
      license_id, account_fingerprint, last_version
    ) values (
      v_license.id, p_account_fingerprint, p_version
    );
  end if;

  insert into public.aurum_license_events(license_id, key_hash, account_fingerprint, version, decision)
  values (v_license.id, p_key_hash, p_account_fingerprint, p_version, 'VALID');

  return query select 'VALID'::text,
    coalesce(extract(epoch from v_license.expires_at)::bigint, 0::bigint);
end;
$$;

revoke all on function public.aurum_validate_license(text,text,text) from public, anon, authenticated;
grant execute on function public.aurum_validate_license(text,text,text) to service_role;
